export const FETCH_SELECTED_ITEM = "FETCH_SELECTED_ITEM";

export const SET_MEMBER_LOGIN = "SET_MEMBER_LOGIN";
export const SET_MEMBER_LOGOUT = "SET_MEMBER_LOGOUT";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
